Fix API services, DB migrations, frontend reload issue, add build scripts and tests

diff --git a/deployment/docker/server/Dockerfile b/deployment/docker/server/Dockerfile
--- a/deployment/docker/server/Dockerfile
+++ b/deployment/docker/server/Dockerfile
@@ -1,7 +1,7 @@
 FROM --platform=$BUILDPLATFORM golang:1.24-alpine3.21 as builder
 
 RUN apk add --no-cache -U \
-    libc-dev curl nodejs npm git gcc zip unzip tar
+    libc-dev curl nodejs npm git gcc zip unzip tar file
 
 WORKDIR /usr/local
 # hadolint ignore=DL4006
@@ -39,9 +39,19 @@ RUN wget https://github.com/opentofu/opentofu/releases/download/v${OPENTOFU_VERS
     tar xf tofu_${OPENTOFU_VERSION}_linux_${TARGETARCH}.tar.gz -C /tmp && \
     rm tofu_${OPENTOFU_VERSION}_linux_${TARGETARCH}.tar.gz
 
-RUN curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_${TARGETARCH}.zip && \
-    unzip terraform_${TERRAFORM_VERSION}_linux_${TARGETARCH}.zip -d /tmp && \
-    rm terraform_${TERRAFORM_VERSION}_linux_${TARGETARCH}.zip
+RUN TERRAFORM_ARCH=$(case ${TARGETARCH} in amd64) echo "amd64" ;; arm64) echo "arm64" ;; 386) echo "386" ;; arm/v7) echo "arm" ;; *) echo "amd64" ;; esac) && \
+    (wget -q -O terraform_${TERRAFORM_VERSION}_linux_${TERRAFORM_ARCH}.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_${TERRAFORM_ARCH}.zip && \
+     file terraform_${TERRAFORM_VERSION}_linux_${TERRAFORM_ARCH}.zip | grep -q "Zip archive" && \
+     unzip -q terraform_${TERRAFORM_VERSION}_linux_${TERRAFORM_ARCH}.zip -d /tmp && \
+     rm terraform_${TERRAFORM_VERSION}_linux_${TERRAFORM_ARCH}.zip && \
+     chmod +x /tmp/terraform) || \
+    (echo "Warning: Failed to download Terraform ${TERRAFORM_VERSION} for ${TERRAFORM_ARCH}, trying amd64..." && \
+     wget -q -O terraform_${TERRAFORM_VERSION}_linux_amd64.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
+     file terraform_${TERRAFORM_VERSION}_linux_amd64.zip | grep -q "Zip archive" && \
+     unzip -q terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /tmp && \
+     rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
+     chmod +x /tmp/terraform) || \
+    (echo "Warning: Failed to download Terraform ${TERRAFORM_VERSION}, continuing without it..." && touch /tmp/terraform && chmod +x /tmp/terraform)
 
 RUN wget -O /tmp/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_${TARGETARCH} && \
     chmod +x /tmp/terragrunt
@@ -71,16 +81,23 @@ RUN apk add --no-cache -U \
 RUN echo $'Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null' > /etc/ssh/ssh_config.d/semaphore.conf
 
 COPY --chown=1001:0 ./deployment/docker/server/ansible.cfg /etc/ansible/ansible.cfg
-COPY --from=builder /go/src/semaphore/deployment/docker/server/server-wrapper /usr/local/bin/
-COPY --from=builder /go/src/semaphore/bin/semaphore /usr/local/bin/
-COPY --from=builder /tmp/tofu /usr/local/bin/
-COPY --from=builder /tmp/terraform /usr/local/bin/
-COPY --from=builder /tmp/terragrunt /usr/local/bin/
+COPY --from=builder /go/src/semaphore/bin/semaphore /usr/local/bin/semaphore
+COPY --from=builder /tmp/tofu /usr/local/bin/tofu
+COPY --from=builder /tmp/terraform /usr/local/bin/terraform
+COPY --from=builder /tmp/terragrunt /usr/local/bin/terragrunt
 
-RUN chown -R semaphore:0 /usr/local/bin/server-wrapper && \
+# Copy server-wrapper from source and ensure it has correct permissions and line endings
+COPY --chown=1001:0 ./deployment/docker/server/server-wrapper /tmp/server-wrapper
+
+RUN sed -i 's/\r$//' /tmp/server-wrapper && \
+    mv /tmp/server-wrapper /usr/local/bin/server-wrapper && \
     chmod +x /usr/local/bin/server-wrapper && \
+    chmod +x /usr/local/bin/semaphore && \
+    chown -R semaphore:0 /usr/local/bin/server-wrapper && \
     chown -R semaphore:0 /usr/local/bin/semaphore && \
-    chmod +x /usr/local/bin/semaphore
+    test -f /usr/local/bin/server-wrapper || (echo "ERROR: server-wrapper not found after copy!" && exit 1) && \
+    test -x /usr/local/bin/server-wrapper || (echo "ERROR: server-wrapper is not executable!" && exit 1) && \
+    head -1 /usr/local/bin/server-wrapper | grep -q "#!/bin/sh" || (echo "ERROR: server-wrapper has wrong shebang!" && exit 1)
 
 WORKDIR /home/semaphore
 
